#!/bin/python3

import math
import os
import random
import re
import sys

# Complete the insertionSort2 function below.
def insertionSort2(n, arr):
    for t in range(1,len(arr)):
        N = arr[t]
        i = t-1
        while (N<arr[i]) and (i>=0):
            arr[i+1] = arr[i]
            i -= 1
        arr[i+1] = N
        print(*arr)

if __name__ == '__main__':
    n = int(input())

    arr = list(map(int, input().rstrip().split()))

    insertionSort2(n, arr)
